language: ruby
rvm:
- 2.4.0
script:
- yarn install
deploy:
  provider: heroku
  api_key:
    secure: KfZwkqYXWIFm3FXREkFJkTKsspDqAHxna+vwsrc55tbsMXdp8nOyMirWH0vIglezJc7Qzw4ToxAY4yrhb+QhmDtv3FnuJwVAqjyrLyk2mcbibzjCsWTD4RdKB256lA5UIKx8ASrn/63+vZ9xX50GTkCAGJnj7KonnwwSZ5OWFMNYjdq5IFgZ1yuEBHmN4zcnQPd2ZvTZg/ZCaZjjbleIkXFS6U6EZrrMUuQlSVR/j4P2NAMuqZXnNekQE0y3tTPrOIgWJewr2lPepkdfsmlWrZMgh3+MBI60G+TfzhYA8XgWJoc0na+MjJcpNCBwAOfuDz88hn9MlHMOcS5lyZQOd/7fY/aN3kyP9jSV7x0xHm7dwU9vdp3jKOc5Pbfp03JYe91Lw9JDd6iLQNZ4Hp/TpNdIjPzoPZ6PktzALnP5aGN7ypANc5YtE/9tsuPbe29IDUYIH3KJzB4tl3nwXIqcuE0b14r9y6MTyh/ZyGNj/w9VMPP68o/aMBDvhlfOBxnr2IKP5+WoWJUJ+lnD8hK0OrrHIOD/SUUJyCfTKUWVzvk7ClucBq/zHxWfhu/4iuDNqqu/1Jv+rHRfN9iByFpL71Lt4hM1zvd17YFlOWiJjf+BuZTJPx4oYlGOyInSg6g9IQSPdWKRj7Tle3tqowpDLpOevrryRtfMUEldnCgZneA=
  app:
    master: art-culture
    prod: art-culture
  on:
    repo: dben89x/art-culture
  skip_cleanup: true
notifications:
  email: false
